name: PyTorch Trainer Component
description: Train a pytorch model
inputs:
outputs:
- {name: trained_model, type: GCSPath}
implementation:
  container:
    image: gcr.io/voxsrc-2020-dev-1/trainer:latest
    command: [
      python3, /src/voxceleb_trainer/trainSpeakerNet.py,

      --model-save-path,
      {outputPath: trained_model},
    ]
